// ============================================================
// ReserveFlow - サンプルデータ生成
// ============================================================

import { Reservation, Customer, Staff, Settings } from "./types";

function addDays(base: Date, days: number): Date {
  const d = new Date(base);
  d.setDate(d.getDate() + days);
  return d;
}

function withTime(base: Date, hour: number, minute = 0): Date {
  const d = new Date(base);
  d.setHours(hour, minute, 0, 0);
  return d;
}

export function generateSampleData(): {
  reservations: Reservation[];
  customers: Customer[];
  staff: Staff[];
  settings: Settings;
} {
  const today = new Date();
  today.setHours(0, 0, 0, 0);

  // -------------------------------------------------------
  // スタッフ
  // -------------------------------------------------------
  const staff: Staff[] = [
    {
      id: "s1",
      name: "佐藤 美咲",
      role: "シニアアドバイザー",
      email: "sato@reserveflow.demo",
      phone: "090-1234-5678",
      status: "active",
      createdAt: addDays(today, -540).toISOString(),
    },
    {
      id: "s2",
      name: "田中 翔",
      role: "シニアスタッフ",
      email: "tanaka@reserveflow.demo",
      phone: "090-2345-6789",
      status: "active",
      createdAt: addDays(today, -365).toISOString(),
    },
    {
      id: "s3",
      name: "鈴木 彩",
      role: "スタッフ",
      email: "suzuki@reserveflow.demo",
      phone: "090-3456-7890",
      status: "active",
      createdAt: addDays(today, -180).toISOString(),
    },
    {
      id: "s4",
      name: "高橋 健太",
      role: "マネージャー",
      email: "takahashi@reserveflow.demo",
      phone: "090-4567-8901",
      status: "active",
      createdAt: addDays(today, -730).toISOString(),
    },
    {
      id: "s5",
      name: "山本 葵",
      role: "スタッフ",
      email: "yamamoto@reserveflow.demo",
      phone: "090-5678-9012",
      status: "off",
      createdAt: addDays(today, -90).toISOString(),
    },
  ];

  // -------------------------------------------------------
  // 顧客
  // -------------------------------------------------------
  const customers: Customer[] = [
    {
      id: "c1",
      name: "山田 太郎",
      phone: "080-1234-5678",
      email: "yamada@example.com",
      visitCount: 15,
      lastReservationDate: addDays(today, -7).toISOString(),
      tags: ["vip", "repeater"],
      memo: "長期顧客。プレミアムプランを定期ご利用。誕生日割引適用中。",
      createdAt: addDays(today, -500).toISOString(),
    },
    {
      id: "c2",
      name: "佐々木 花子",
      phone: "080-2345-6789",
      email: "sasaki@example.com",
      visitCount: 7,
      lastReservationDate: addDays(today, -14).toISOString(),
      tags: ["repeater"],
      memo: "毎月第2週に来店。スタンダードプランご利用。",
      createdAt: addDays(today, -240).toISOString(),
    },
    {
      id: "c3",
      name: "中村 翔太",
      phone: "080-3456-7890",
      email: "nakamura@example.com",
      visitCount: 2,
      lastReservationDate: today.toISOString(),
      tags: ["new"],
      memo: "初回来店。丁寧な案内が必要。次回はスタンダードプランを提案。",
      createdAt: addDays(today, -5).toISOString(),
    },
    {
      id: "c4",
      name: "小林 優子",
      phone: "080-4567-8901",
      email: "kobayashi@example.com",
      visitCount: 10,
      lastReservationDate: addDays(today, -3).toISOString(),
      tags: ["vip", "repeater"],
      memo: "アレルギー（花粉・ほこり）あり。事前に確認を。VIP対応必須。",
      createdAt: addDays(today, -400).toISOString(),
    },
    {
      id: "c5",
      name: "加藤 直樹",
      phone: "080-5678-9012",
      email: "kato@example.com",
      visitCount: 4,
      lastReservationDate: addDays(today, 1).toISOString(),
      tags: ["repeater"],
      memo: "",
      createdAt: addDays(today, -150).toISOString(),
    },
    {
      id: "c6",
      name: "渡辺 美穂",
      phone: "080-6789-0123",
      email: "watanabe@example.com",
      visitCount: 1,
      lastReservationDate: addDays(today, -2).toISOString(),
      tags: ["new", "caution"],
      memo: "過去に無断キャンセル1回あり。次回キャンセルで要対応。",
      createdAt: addDays(today, -30).toISOString(),
    },
    {
      id: "c7",
      name: "伊藤 健",
      phone: "080-7890-1234",
      email: "ito@example.com",
      visitCount: 18,
      lastReservationDate: addDays(today, -5).toISOString(),
      tags: ["vip", "repeater"],
      memo: "オンライン相談を定期的にご利用。出張が多いためオンライン希望。",
      createdAt: addDays(today, -600).toISOString(),
    },
    {
      id: "c8",
      name: "松本 愛",
      phone: "080-8901-2345",
      email: "matsumoto@example.com",
      visitCount: 3,
      lastReservationDate: addDays(today, 7).toISOString(),
      tags: ["repeater"],
      memo: "定期メンテナンスで2ヶ月に1回来店。",
      createdAt: addDays(today, -100).toISOString(),
    },
    {
      id: "c9",
      name: "西村 拓也",
      phone: "080-9012-3456",
      email: "nishimura@example.com",
      visitCount: 0,
      lastReservationDate: "",
      tags: ["new"],
      memo: "Web経由で問い合わせ。初回カウンセリングを案内済み。",
      createdAt: addDays(today, -1).toISOString(),
    },
    {
      id: "c10",
      name: "岡田 綾",
      phone: "080-0123-4567",
      email: "okada@example.com",
      visitCount: 6,
      lastReservationDate: addDays(today, -20).toISOString(),
      tags: ["repeater"],
      memo: "",
      createdAt: addDays(today, -200).toISOString(),
    },
  ];

  // -------------------------------------------------------
  // 予約（今日・直近・過去・来月）
  // -------------------------------------------------------
  const reservations: Reservation[] = [
    // ---- 今日 ----
    {
      id: "r01",
      dateTime: withTime(today, 10, 0).toISOString(),
      customerId: "c3",
      customerName: "中村 翔太",
      staffId: "s1",
      staffName: "佐藤 美咲",
      serviceName: "初回カウンセリング",
      amount: 5000,
      status: "visited",
      memo: "好印象。次回スタンダードプランを提案済み。",
      createdAt: addDays(today, -5).toISOString(),
    },
    {
      id: "r02",
      dateTime: withTime(today, 13, 0).toISOString(),
      customerId: "c1",
      customerName: "山田 太郎",
      staffId: "s2",
      staffName: "田中 翔",
      serviceName: "プレミアムプラン",
      amount: 20000,
      status: "visited",
      memo: "",
      createdAt: addDays(today, -7).toISOString(),
    },
    {
      id: "r03",
      dateTime: withTime(today, 15, 0).toISOString(),
      customerId: "c2",
      customerName: "佐々木 花子",
      staffId: "s3",
      staffName: "鈴木 彩",
      serviceName: "スタンダードプラン",
      amount: 10000,
      status: "reserved",
      memo: "",
      createdAt: addDays(today, -5).toISOString(),
    },
    {
      id: "r04",
      dateTime: withTime(today, 17, 0).toISOString(),
      customerId: "c4",
      customerName: "小林 優子",
      staffId: "s1",
      staffName: "佐藤 美咲",
      serviceName: "定期メンテナンス",
      amount: 8000,
      status: "reserved",
      memo: "アレルギー確認済み。VIP対応。",
      createdAt: addDays(today, -10).toISOString(),
    },
    // ---- 明日 ----
    {
      id: "r05",
      dateTime: withTime(addDays(today, 1), 10, 0).toISOString(),
      customerId: "c5",
      customerName: "加藤 直樹",
      staffId: "s2",
      staffName: "田中 翔",
      serviceName: "スタンダードプラン",
      amount: 10000,
      status: "reserved",
      memo: "",
      createdAt: addDays(today, -5).toISOString(),
    },
    {
      id: "r06",
      dateTime: withTime(addDays(today, 1), 14, 0).toISOString(),
      customerId: "c7",
      customerName: "伊藤 健",
      staffId: "s4",
      staffName: "高橋 健太",
      serviceName: "オンライン相談",
      amount: 3000,
      status: "reserved",
      memo: "Zoomリンクを事前に送付すること。",
      createdAt: addDays(today, -3).toISOString(),
    },
    // ---- 2日後 ----
    {
      id: "r07",
      dateTime: withTime(addDays(today, 2), 11, 0).toISOString(),
      customerId: "c8",
      customerName: "松本 愛",
      staffId: "s3",
      staffName: "鈴木 彩",
      serviceName: "スタンダードプラン",
      amount: 10000,
      status: "reserved",
      memo: "",
      createdAt: addDays(today, -7).toISOString(),
    },
    {
      id: "r08",
      dateTime: withTime(addDays(today, 2), 15, 30).toISOString(),
      customerId: "c10",
      customerName: "岡田 綾",
      staffId: "s1",
      staffName: "佐藤 美咲",
      serviceName: "定期メンテナンス",
      amount: 8000,
      status: "reserved",
      memo: "",
      createdAt: addDays(today, -6).toISOString(),
    },
    // ---- 3〜5日後 ----
    {
      id: "r09",
      dateTime: withTime(addDays(today, 3), 10, 0).toISOString(),
      customerId: "c4",
      customerName: "小林 優子",
      staffId: "s4",
      staffName: "高橋 健太",
      serviceName: "プレミアムプラン",
      amount: 20000,
      status: "reserved",
      memo: "VIP対応。入口でのお出迎えを忘れずに。",
      createdAt: addDays(today, -4).toISOString(),
    },
    {
      id: "r10",
      dateTime: withTime(addDays(today, 4), 13, 0).toISOString(),
      customerId: "c1",
      customerName: "山田 太郎",
      staffId: "s2",
      staffName: "田中 翔",
      serviceName: "プレミアムプラン",
      amount: 20000,
      status: "reserved",
      memo: "",
      createdAt: addDays(today, -3).toISOString(),
    },
    {
      id: "r11",
      dateTime: withTime(addDays(today, 5), 10, 0).toISOString(),
      customerId: "c6",
      customerName: "渡辺 美穂",
      staffId: "s3",
      staffName: "鈴木 彩",
      serviceName: "初回カウンセリング",
      amount: 5000,
      status: "reserved",
      memo: "前回無断キャンセルあり。前日にリマインド送付を。",
      createdAt: addDays(today, -2).toISOString(),
    },
    // ---- 来週 ----
    {
      id: "r12",
      dateTime: withTime(addDays(today, 7), 10, 0).toISOString(),
      customerId: "c8",
      customerName: "松本 愛",
      staffId: "s1",
      staffName: "佐藤 美咲",
      serviceName: "プレミアムプラン",
      amount: 20000,
      status: "reserved",
      memo: "",
      createdAt: addDays(today, -2).toISOString(),
    },
    {
      id: "r13",
      dateTime: withTime(addDays(today, 10), 13, 0).toISOString(),
      customerId: "c4",
      customerName: "小林 優子",
      staffId: "s2",
      staffName: "田中 翔",
      serviceName: "定期メンテナンス",
      amount: 8000,
      status: "reserved",
      memo: "",
      createdAt: addDays(today, -1).toISOString(),
    },
    {
      id: "r14",
      dateTime: withTime(addDays(today, 12), 11, 0).toISOString(),
      customerId: "c7",
      customerName: "伊藤 健",
      staffId: "s1",
      staffName: "佐藤 美咲",
      serviceName: "オンライン相談",
      amount: 3000,
      status: "reserved",
      memo: "",
      createdAt: addDays(today, -1).toISOString(),
    },
    // ---- 来月 ----
    {
      id: "r15",
      dateTime: withTime(addDays(today, 32), 10, 0).toISOString(),
      customerId: "c7",
      customerName: "伊藤 健",
      staffId: "s4",
      staffName: "高橋 健太",
      serviceName: "オンライン相談",
      amount: 3000,
      status: "reserved",
      memo: "",
      createdAt: today.toISOString(),
    },
    {
      id: "r16",
      dateTime: withTime(addDays(today, 35), 14, 0).toISOString(),
      customerId: "c1",
      customerName: "山田 太郎",
      staffId: "s1",
      staffName: "佐藤 美咲",
      serviceName: "プレミアムプラン",
      amount: 20000,
      status: "reserved",
      memo: "",
      createdAt: today.toISOString(),
    },
    // ---- 過去（昨日〜直近1週間）----
    {
      id: "r17",
      dateTime: withTime(addDays(today, -1), 10, 0).toISOString(),
      customerId: "c1",
      customerName: "山田 太郎",
      staffId: "s1",
      staffName: "佐藤 美咲",
      serviceName: "プレミアムプラン",
      amount: 20000,
      status: "visited",
      memo: "",
      createdAt: addDays(today, -8).toISOString(),
    },
    {
      id: "r18",
      dateTime: withTime(addDays(today, -2), 14, 0).toISOString(),
      customerId: "c6",
      customerName: "渡辺 美穂",
      staffId: "s2",
      staffName: "田中 翔",
      serviceName: "スタンダードプラン",
      amount: 10000,
      status: "no_show",
      memo: "連絡なし。翌日フォローアップの電話を実施。",
      createdAt: addDays(today, -9).toISOString(),
    },
    {
      id: "r19",
      dateTime: withTime(addDays(today, -3), 11, 0).toISOString(),
      customerId: "c4",
      customerName: "小林 優子",
      staffId: "s3",
      staffName: "鈴木 彩",
      serviceName: "定期メンテナンス",
      amount: 8000,
      status: "visited",
      memo: "",
      createdAt: addDays(today, -10).toISOString(),
    },
    {
      id: "r20",
      dateTime: withTime(addDays(today, -4), 15, 0).toISOString(),
      customerId: "c7",
      customerName: "伊藤 健",
      staffId: "s4",
      staffName: "高橋 健太",
      serviceName: "オンライン相談",
      amount: 3000,
      status: "visited",
      memo: "",
      createdAt: addDays(today, -11).toISOString(),
    },
    {
      id: "r21",
      dateTime: withTime(addDays(today, -5), 10, 0).toISOString(),
      customerId: "c2",
      customerName: "佐々木 花子",
      staffId: "s1",
      staffName: "佐藤 美咲",
      serviceName: "スタンダードプラン",
      amount: 10000,
      status: "visited",
      memo: "",
      createdAt: addDays(today, -12).toISOString(),
    },
    {
      id: "r22",
      dateTime: withTime(addDays(today, -6), 13, 0).toISOString(),
      customerId: "c5",
      customerName: "加藤 直樹",
      staffId: "s2",
      staffName: "田中 翔",
      serviceName: "スタンダードプラン",
      amount: 10000,
      status: "cancelled",
      memo: "急な出張により前日キャンセル。次回予約済み。",
      createdAt: addDays(today, -13).toISOString(),
    },
    {
      id: "r23",
      dateTime: withTime(addDays(today, -7), 10, 0).toISOString(),
      customerId: "c1",
      customerName: "山田 太郎",
      staffId: "s4",
      staffName: "高橋 健太",
      serviceName: "プレミアムプラン",
      amount: 20000,
      status: "visited",
      memo: "",
      createdAt: addDays(today, -14).toISOString(),
    },
    // ---- 2〜4週間前 ----
    {
      id: "r24",
      dateTime: withTime(addDays(today, -10), 14, 0).toISOString(),
      customerId: "c10",
      customerName: "岡田 綾",
      staffId: "s3",
      staffName: "鈴木 彩",
      serviceName: "スタンダードプラン",
      amount: 10000,
      status: "visited",
      memo: "",
      createdAt: addDays(today, -17).toISOString(),
    },
    {
      id: "r25",
      dateTime: withTime(addDays(today, -12), 10, 0).toISOString(),
      customerId: "c7",
      customerName: "伊藤 健",
      staffId: "s1",
      staffName: "佐藤 美咲",
      serviceName: "オンライン相談",
      amount: 3000,
      status: "visited",
      memo: "",
      createdAt: addDays(today, -19).toISOString(),
    },
    {
      id: "r26",
      dateTime: withTime(addDays(today, -14), 11, 0).toISOString(),
      customerId: "c3",
      customerName: "中村 翔太",
      staffId: "s3",
      staffName: "鈴木 彩",
      serviceName: "初回カウンセリング",
      amount: 5000,
      status: "visited",
      memo: "",
      createdAt: addDays(today, -20).toISOString(),
    },
    {
      id: "r27",
      dateTime: withTime(addDays(today, -16), 15, 0).toISOString(),
      customerId: "c8",
      customerName: "松本 愛",
      staffId: "s2",
      staffName: "田中 翔",
      serviceName: "定期メンテナンス",
      amount: 8000,
      status: "visited",
      memo: "",
      createdAt: addDays(today, -23).toISOString(),
    },
    {
      id: "r28",
      dateTime: withTime(addDays(today, -18), 10, 0).toISOString(),
      customerId: "c4",
      customerName: "小林 優子",
      staffId: "s4",
      staffName: "高橋 健太",
      serviceName: "プレミアムプラン",
      amount: 20000,
      status: "visited",
      memo: "VIP対応。大変満足されていた。",
      createdAt: addDays(today, -25).toISOString(),
    },
    {
      id: "r29",
      dateTime: withTime(addDays(today, -20), 13, 0).toISOString(),
      customerId: "c2",
      customerName: "佐々木 花子",
      staffId: "s1",
      staffName: "佐藤 美咲",
      serviceName: "スタンダードプラン",
      amount: 10000,
      status: "visited",
      memo: "",
      createdAt: addDays(today, -27).toISOString(),
    },
    // ---- 1〜2ヶ月前（グラフ用） ----
    {
      id: "r30",
      dateTime: withTime(addDays(today, -33), 10, 0).toISOString(),
      customerId: "c1",
      customerName: "山田 太郎",
      staffId: "s2",
      staffName: "田中 翔",
      serviceName: "プレミアムプラン",
      amount: 20000,
      status: "visited",
      memo: "",
      createdAt: addDays(today, -40).toISOString(),
    },
    {
      id: "r31",
      dateTime: withTime(addDays(today, -35), 14, 0).toISOString(),
      customerId: "c5",
      customerName: "加藤 直樹",
      staffId: "s3",
      staffName: "鈴木 彩",
      serviceName: "スタンダードプラン",
      amount: 10000,
      status: "visited",
      memo: "",
      createdAt: addDays(today, -42).toISOString(),
    },
    {
      id: "r32",
      dateTime: withTime(addDays(today, -38), 11, 0).toISOString(),
      customerId: "c7",
      customerName: "伊藤 健",
      staffId: "s1",
      staffName: "佐藤 美咲",
      serviceName: "オンライン相談",
      amount: 3000,
      status: "visited",
      memo: "",
      createdAt: addDays(today, -45).toISOString(),
    },
    {
      id: "r33",
      dateTime: withTime(addDays(today, -40), 10, 0).toISOString(),
      customerId: "c4",
      customerName: "小林 優子",
      staffId: "s4",
      staffName: "高橋 健太",
      serviceName: "プレミアムプラン",
      amount: 20000,
      status: "visited",
      memo: "",
      createdAt: addDays(today, -47).toISOString(),
    },
    {
      id: "r34",
      dateTime: withTime(addDays(today, -42), 15, 0).toISOString(),
      customerId: "c10",
      customerName: "岡田 綾",
      staffId: "s3",
      staffName: "鈴木 彩",
      serviceName: "定期メンテナンス",
      amount: 8000,
      status: "visited",
      memo: "",
      createdAt: addDays(today, -49).toISOString(),
    },
    {
      id: "r35",
      dateTime: withTime(addDays(today, -55), 10, 0).toISOString(),
      customerId: "c1",
      customerName: "山田 太郎",
      staffId: "s1",
      staffName: "佐藤 美咲",
      serviceName: "プレミアムプラン",
      amount: 20000,
      status: "visited",
      memo: "",
      createdAt: addDays(today, -62).toISOString(),
    },
    {
      id: "r36",
      dateTime: withTime(addDays(today, -58), 14, 0).toISOString(),
      customerId: "c2",
      customerName: "佐々木 花子",
      staffId: "s2",
      staffName: "田中 翔",
      serviceName: "スタンダードプラン",
      amount: 10000,
      status: "visited",
      memo: "",
      createdAt: addDays(today, -65).toISOString(),
    },
    {
      id: "r37",
      dateTime: withTime(addDays(today, -62), 11, 0).toISOString(),
      customerId: "c8",
      customerName: "松本 愛",
      staffId: "s3",
      staffName: "鈴木 彩",
      serviceName: "スタンダードプラン",
      amount: 10000,
      status: "visited",
      memo: "",
      createdAt: addDays(today, -69).toISOString(),
    },
    {
      id: "r38",
      dateTime: withTime(addDays(today, -70), 10, 0).toISOString(),
      customerId: "c7",
      customerName: "伊藤 健",
      staffId: "s4",
      staffName: "高橋 健太",
      serviceName: "オンライン相談",
      amount: 3000,
      status: "visited",
      memo: "",
      createdAt: addDays(today, -77).toISOString(),
    },
    {
      id: "r39",
      dateTime: withTime(addDays(today, -75), 13, 0).toISOString(),
      customerId: "c5",
      customerName: "加藤 直樹",
      staffId: "s1",
      staffName: "佐藤 美咲",
      serviceName: "スタンダードプラン",
      amount: 10000,
      status: "cancelled",
      memo: "3日前にキャンセル連絡あり。",
      createdAt: addDays(today, -82).toISOString(),
    },
    {
      id: "r40",
      dateTime: withTime(addDays(today, -80), 10, 0).toISOString(),
      customerId: "c4",
      customerName: "小林 優子",
      staffId: "s2",
      staffName: "田中 翔",
      serviceName: "定期メンテナンス",
      amount: 8000,
      status: "visited",
      memo: "",
      createdAt: addDays(today, -87).toISOString(),
    },
  ];

  const settings: Settings = {
    storeName: "ReserveFlow サンプル店",
    openTime: "09:00",
    closeTime: "20:00",
    closedDays: ["日"],
    reservationUnit: 60,
    cancellationDeadline: 24,
    notificationEmail: "admin@example.com",
  };

  return { reservations, customers, staff, settings };
}
